export const stationConstant = {
  STATION_GET_ALL_SUCCESS: 'STATION_GET_ALL_SUCCESS',
  STATION_GET_ALL_FAILURE: 'STATION_GET_ALL_FAILURE',
};
export const loginConstant = {
  LOGIN_REQUESTING: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};
export const registerConstant = {
  LOGIN_REQUESTING: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};
